### ISSUE TITLE
Site can't be reached

### ISSUE THREAD

**Issue by AniGP** [cs540-24/news#1]
- Also, please get login at formerly known ACF ([https://www.nics.utk.edu/account-requests](https://www.nics.utk.edu/account-requests))

I don't know why, but I am not able to open this site

**Comment by seeker-3** [comment]
Is that the right URL? [https://portal.acf.utk.edu/user_requests](https://portal.acf.utk.edu/user_requests/new_user/netid/)

**Comment by audrism** [comment]
yes :-)
